name: carp_backend
description: CARP data backend for the CARP sensing framework
version: 0.0.1
author: CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing/tree/master/flutter/carp_backend

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.0.0
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:       # used to build JSON serialization .g files
  json_serializable: ^1.0.0

# The following section is specific to Flutter.
flutter:
