name: carp_firebase_backend
description: Firebase data backend for CARP sensing in Flutter
version: 0.0.1
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing/tree/master/flutter/carp_firebase_backend

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.0.0
  #http:
  google_sign_in: ^3.0.5
  firebase_storage: ^1.0.2
  firebase_auth: ^0.5.20
  carp_mobile_sensing: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:       # used to build JSON serialization .g files
  json_serializable: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

