name: carp_context_package
description: CARP context sampling package. Samples location, activity, and weather.
version: 0.3.4
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_context_package

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.0.0
  carp_mobile_sensing: ^0.3.10
  weather: ^0.1.0
  location: ^1.4.1
  activity_recognition: ^0.1.3

# Overriding carp libraries to use the local copy
# Remove this when done development
#dependency_overrides:
#  carp_mobile_sensing:
#    path: ../carp_mobile_sensing/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^1.0.0
  test:

# The following section is specific to Flutter.
flutter:
