name: carp_mobile_sensing_core
description: CARP Mobile Sensing Framework in Flutter
version: 0.0.1
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing/tree/master/flutter/carp_firebase_backend

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  system_info:
  sensors: ^0.3.4
  battery:
  connectivity:
  flutter_blue: # <- Gives build errors on android, see issue tracker
  oauth2:
  uuid: ^1.0.0
  device_info:
  json_annotation: ^1.0.0
  location:
  path_provider:
  archive: ^2.0.4
  google_sign_in: ^3.0.5
  firebase_storage: ^1.0.2
  firebase_auth: ^0.5.20
  pedometer:
  light: # Light sensor over platform channel
  device_apps: # Device installed apps over platform channel
  sms: # Sms messages over platform channel
  screen_state:

  #phone_log:   # phone_log does not support Dart 2.0 >> have raised an issues, but not used until this is fixed.

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^1.0.0


# The following section is specific to Flutter.
flutter:
#  plugin:
#    androidPackage: dk.cachet.carpsensing
#    pluginClass: CarpSensingPlugin

